repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
    -   id: nbqa-black
    -   id: nbqa-isort
        args: ["--float-to-top"]
-   repo: https://github.com/kynan/nbstripout
    rev: main
    hooks:
    -   id: nbstripout
        files: ".ipynb"
